///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/Demo.aks
/// Generation time: dom oct 28 13:57:49 CET 2018
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x65B7
#define song_ingame_size     139
#define song_ingame_end      0x6641

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
