///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/Demo.aks
/// Generation time: lun oct 29 04:44:36 CET 2018
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x6705
#define song_ingame_size     139
#define song_ingame_end      0x678f

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
